### ISSUE TITLE
Working on Win 10 ?

### ISSUE THREAD

**Issue by flaviu22** [vitalif/ntfs-3g#3]
When I read your specs regarding this library I guess I understood why didn't worked this code on my Win 10 on NTFS drives ... what should I do in order to use it on Win10 too ? It is possible ? If it is, how ?

What didn't worked ?

on **volume.c**, inside of **ntfs_volume_startup** function, there is a call

if (! ntfs_boot_sector_is_ntfs(bs))

```
BOOL ntfs_boot_sector_is_ntfs(NTFS_BOOT_SECTOR* b)
{
	u32 i;
	BOOL ret = FALSE;
	ntfs_log_debug("Beginning bootsector check.\n");

	ntfs_log_debug("Checking OEMid, NTFS signature.\n");
	if (b->oem_id != const_cpu_to_le64(0x202020205346544eULL))	// "NTFS    "
	{
		ntfs_log_error("NTFS signature is missing.\n");  // <-- here is going my code, even my NTFS drives is perfectly ok ... why ?
		goto not_ntfs;
	}
...

```
P.S. This is not an issue, is more a question/asking :)

**Comment by zefr0x** [comment]
Just read the first paragraph in the [README](https://github.com/vitalif/ntfs-3g/blob/04d4b37a9a6c992d89c93193d0abdd13ab1f2931/README).

It is not a windows driver
